name: hadrmouthamza
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_bloc:
  shared_preferences:
  cached_network_image:
  flutter_svg:
  equatable:
  pin_code_fields:
  carousel_slider:
  smooth_page_indicator:
  dotted_border:
  sms_autofill:
  firebase_core:
  get_it:
  json_annotation:
  freezed_annotation:
  intl:
  macos_ui:
  font_awesome_flutter:
  flutter_screenutil:
  responsive_framework:
  image_picker:
  fluttertoast:
  go_router:
  gap:
  url_strategy:
  firebase_auth:
  cloud_firestore:
  flutter_staggered_animations:
  location:
  fl_chart:
  badges:
  flutter_rounded_date_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  freezed:
  json_serializable:
  build_runner:
  flutter_native_splash:

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/CairoSemiBold.ttf
          weight: 600
        - asset: assets/fonts/CairoMedium.ttf
          weight: 500
        - asset: assets/fonts/CairoBold.ttf
          weight: 700
        - asset: assets/fonts/CairoRegular.ttf
          weight: 400

    - family: Lalezar
      fonts:
        - asset: assets/fonts/LalezarRegular.ttf
          weight: 400
